name: Build & Test App

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!i18n/src/commonMain/moko-resources/**/strings.xml'
      - '!i18n/src/commonMain/moko-resources/**/plurals.xml'
      - 'i18n/src/commonMain/moko-resources/base/strings.xml'
      - 'i18n/src/commonMain/moko-resources/base/plurals.xml'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: Build, Test & (on main) Sign APK
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Count Commits
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          git rev-list --count HEAD
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          echo "${{ env.COMMIT_COUNT }}"
          test ${{ env.COMMIT_COUNT }} -gt 1 || exit 1

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK / build tools
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Build release APK(s) (unsigned)
        run: ./gradlew assembleNightly -Penable-updater

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Upload test report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: test-report-${{ github.sha }}
          path: app/build/reports/tests/testReleaseUnitTest

      - name: Decode keystore
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Sign all nightly APKs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        run: |
          for apk in app/build/outputs/apk/nightly/*.apk; do
            echo "Signing $apk"
            $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
              --ks release.keystore \
              --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
              --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
              --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
              "$apk"
          done

      - name: Clean up build artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        run: |
          set -e

          mv app/build/outputs/apk/nightly/app-universal-nightly.apk tsundoku-r${{ env.COMMIT_COUNT }}.apk
          mv app/build/outputs/apk/nightly/app-arm64-v8a-nightly.apk tsundoku-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
          mv app/build/outputs/apk/nightly/app-armeabi-v7a-nightly.apk tsundoku-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
          mv app/build/outputs/apk/nightly/app-x86-nightly.apk tsundoku-x86-r${{ env.COMMIT_COUNT }}.apk
          mv app/build/outputs/apk/nightly/app-x86_64-nightly.apk tsundoku-x86_64-r${{ env.COMMIT_COUNT }}.apk


      - name: Upload signed APKs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        uses: actions/upload-artifact@v5
        with:
          name: signed-apks-${{ github.sha }}
          path: app/build/outputs/apk/release/*.apk


      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          repository: tsundoku-otaku/tsundoku-nightly
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Tsundoku Nightly r${{ env.COMMIT_COUNT }}
          body: |
            All Hope Abandon Ye Who Enter Here

            <!-->
            > [!TIP]
            >
            > ### If you are unsure which version to download then go with `tsundoku-r${{ env.COMMIT_COUNT }}.apk`
          files: |
            tsundoku-r${{ env.COMMIT_COUNT }}.apk
            tsundoku-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
            tsundoku-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
            tsundoku-x86-r${{ env.COMMIT_COUNT }}.apk
            tsundoku-x86_64-r${{ env.COMMIT_COUNT }}.apk
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TSUNDOKU_BOT_TOKEN }}

      - name: Prune old releases
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'tsundoku-otaku/tsundoku'
        uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe # v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.TSUNDOKU_BOT_TOKEN }}
        with:
          repo: tsundoku-otaku/tsundoku-nightly
          keep_latest: 28
          delete_tags: true

      - name: Cleanup keystore
        if: always()
        run: rm -f release.keystore
